repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.1
    hooks:
    - id: trailing-whitespace
    - id: check-yaml
    - id: check-json
    - id: check-added-large-files
    - id: detect-aws-credentials
    - id: mixed-line-ending

- repo: git://github.com/antonbabenko/pre-commit-terraform
  rev: v1.26.0
  hooks:
    - id: terraform_fmt
    - id: terraform_docs
